# Generated by Django 5.2.15 on 2026-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagecategory",
            options={
                "managed": False,
                "ordering": ["sort", "id"],
                "verbose_name": "图片分类",
                "verbose_name_plural": "图片分类",
            },
        ),
        migrations.AlterModelOptions(
            name="imageinfo",
            options={
                "managed": False,
                "ordering": ["-upload_time", "-id"],
                "verbose_name": "图片信息",
                "verbose_name_plural": "图片信息",
            },
        ),
    ]
