# Generated by Django 5.2.15 on 2026-06-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operatelog",
            options={
                "managed": False,
                "ordering": ["-create_time", "-id"],
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
            },
        ),
    ]
