# Generated by Django 5.2.15 on 2026-06-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sysuser",
            options={
                "managed": False,
                "verbose_name": "系统用户",
                "verbose_name_plural": "系统用户",
            },
        ),
    ]
